# Generated by Django 3.2.16 on 2022-12-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20221206_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genres',
            field=models.IntegerField(choices=[('HORROR', 'Horror'), ('COMEDY', 'Comedy'), ('SCI-FI', 'Sci-fi'), ('FANTASY', 'Fantasy'), ('ACTION', 'Action'), ('ROMANTING', 'Romantic'), ('THRILLER', 'Thriller'), ('OTHER', 'Other')], default=0),
        ),
    ]
