# Generated by Django 3.2.16 on 2022-12-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='genres',
            new_name='genre',
        ),
    ]
