# Generated by Django 3.2.16 on 2022-12-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_genres_post_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.IntegerField(choices=[(0, 'Horror'), (1, 'Comedy'), (2, 'Sci-fi'), (3, 'Fantasy'), (4, 'Action'), (5, 'Romantic'), (6, 'Thriller'), (7, 'Other')], default=0),
        ),
    ]
