# Generated by Django 3.2.16 on 2022-12-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(choices=[('HORROR', 'Horror'), ('COMEDY', 'Comedy'), ('SCI-FI', 'Sci-fi'), ('FANTASY', 'Fantasy'), ('ACTION', 'Action'), ('ROMANTING', 'Romantic'), ('THRILLER', 'Thriller'), ('OTHER', 'Other')], default='HORROR', max_length=50),
        ),
    ]
